POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "Thanos"
}

###
GET http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/enemy/Thanos HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/Thanos HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/Thanos HTTP/1.1
content-type: application/json

{
    "nickname": "Thanos de Titã"
}